#!/bin/sh
echo "#############################################"
echo "Grant root permission either script won't work"
echo "#############################################"

#core package
sudo apt install apt-transport-https ca-certificates curl software-properties-common git jq

#installing docker
#curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add –
#sudo add-apt-repository “deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable”
#sudo apt update
#sudo apt install docker.io 

# install docker
sudo apt update
sudo apt -y install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo apt update
apt-cache policy docker-ce
sudo apt -y install docker-ce
sudo chmod 666 /var/run/docker.sock
docker ps

# install docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-aarch64" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version


#script
sudo git clone https://postalserver.io/start/install /opt/postal/install

sudo ln -s /opt/postal/install/bin/postal /usr/bin/postalserver

#docker engine for DB
sudo docker run -d \
   --name postal-mariadb \
   -p 127.0.0.1:3306:3306 \
   --restart always \
   -e MARIADB_DATABASE=postal \
   -e MARIADB_ROOT_PASSWORD=postal \
   MARIADB_ROOT_PASSWORD
   
sudo docker run -d \
   --name postal-rabbitmq \
   -p 127.0.0.1:5672:5672 \
   --restart always \
   -e RABBITMQ_DEFAULT_USER=postal \
   -e RABBITMQ_DEFAULT_PASS=postal \
   -e RABBITMQ_DEFAULT_VHOST=postal \
   rabbitmq:3.8
   

#getting my configuration
#git clone https://github.com/postalconf.git /opt/postal/config
sudo cp Caddyfile /opt/postal/config
sudo cp postal.yml /opt/postal/config
sudo cp signing.key/opt/postal/config

#staring postal for production 
postal initialize
postal make-user

sudo docker run -d \
   --name postal-caddy \
   --restart always \
   --network host \
   -v /opt/postal/config/Caddyfile:/etc/caddy/Caddyfile \
   -v /opt/postal/caddy-data:/data \
   caddy-data